#!/usr/bin/python

################################################################################
#
# Refer to "LICENSE" for licensing information
#
# Author: John Skubic
# Email:  skubicjj@gmail.com
# Date:   12/16/17 
#
# Description: 
#
################################################################################


# START HOP OPTIONS

HOP_AA_IDX = 0
HOP_ID_IDX = 1

legal_hops = {
"Ahtanum"               : [5.5,   0],
"Amarillo"              : [8.6,   1],
"Aquila"                : [7,     2],
"B. C. Goldings"        : [5,     3],
"Banner"                : [10,    4],
"Bramling Cross"        : [6.5,   5],
"Brewer's Gold"         : [9,     6],
"Bullion"               : [7.5,   7],
"Cascade"               : [7,     8],
"Centennial"            : [7.8,   9],
"Challenger"            : [8.5,   10],
"Chinook"               : [13,    11],
"Citra"                 : [11,    12],
"Cluster"               : [6.5,   13],
"Columbus"              : [15,    14],
"Comet"                 : [10,    15],
"Crystal"               : [4.3,   16],
"Domesic Hallertau"     : [3.9,   17],
"East Kent Goldings"    : [5,     18],
"Eroica"                : [12,    19],
"First Gold"            : [7.5,   20],
"Fuggles"               : [4.5,   21],
"Galena"                : [13,    22],
"Glacier"               : [5.5,   23],
"Goldings"              : [4.5,   24],
"Hallertau Mittelfruh"  : [3.75,  25],
"Hallertau Hersbrucker" : [4,     26],
"Herald"                : [12,    27],
"Hersbrucker"           : [4,     28],
"Horizon"               : [12.5,  29],
"Huller Bitterer"       : [5.75,  30],
"Kent Goldings"         : [5,     31],
"Liberty"               : [4,     32],
"Lublin"                : [4.5,   33],
"Magnum"                : [15,    34],
"Millenium"             : [15.5,  35],
"Mount Hood"            : [4.8,   36],
"Mount Rainier"         : [6.2,   37],
"Motueka"               : [7.0,   38],
"Nelson Sauvin"         : [12.5,  39],
"Newport"               : [15.5,  40],
"Northdown"             : [8.6,   41],
"Northern Brewer"       : [7.8,   42],
"Nugget"                : [14,    43],
"Olympic"               : [12,    44],
"Omega"                 : [10,    45],
"Orion"                 : [7,     46],
"Pacific Gem"           : [15.4,  47],
"Perle"                 : [8.2,   48],
"Phoenix"               : [10,    49],
"Pioneer"               : [9,     50],
"Pride of Ringwood"     : [10,    51],
"Progress"              : [6.25,  52],
"Record"                : [6.5,   53],
"Saaz"                  : [3.5,   54],
"Santiam"               : [6.5,   55],
"Satus"                 : [13,    56],
"Simcoe"                : [12.7,  57],
"Sorachi Ace"           : [11.1,  58],
"Spalt"                 : [4.5,   59],
"Sterling"              : [8.7,   60],
"Sticklebract"          : [11.5,  61],
"Strisselspalt"         : [3.5,   62],
"Styrian Goldings"      : [5.5,   63],
"Super Alpha"           : [13,    64],
"Super Styrians"        : [9,     65],
"Summit"                : [18.5,  66],
"Talisman"              : [8,     67],
"Target"                : [11.5,  68],
"Tettnanger"            : [4.5,   69],
"Tomahawk"              : [15,    70],
"Ultra"                 : [4.5,   71],
"Vanguard"              : [5,     72],
"Warrior"               : [16,    73],
"Whitbread Golding"     : [6,     74],
"Willamette"            : [4.5,   75],
"Wye Target"            : [10,    76],
"Yamhill Goldings"      : [4,     77],
"Yakima Cluster"        : [7,     78],
"Yeoman"                : [7.25,  79],
"Zenith"                : [9,     80],
"Zeus"                  : [16,    81]
}


# START FERMENTABLES 

FERMENTABLES_TYPE_IDX     = 0
FERMENTABLES_SUBTYPE_IDX  = 1
FERMENTABLES_COLOR_IDX    = 2
FERMENTABLES_PPG_IDX      = 3
FERMENTABLES_ID_IDX       = 4

legal_fermentables = {
"Abbey Malt"                                   :["Grain",           "Base malt",        17      , 33,   0],
"Acerola"                                      :["Fruit",           "Fruit",            0       , 1.5,  1],
"Acidulated Malt"                              :["Grain",           "Acidulated malt",  3.4     , 27,   2],
"Ale Malt"                                     :["Grain",           "Base malt",        3.04569 , 37.4, 3],
"Ale Malt"                                     :["Grain",           "Base malt",        3       , 37,   4],
"Amber"                                        :["Grain",           "Base malt",        27      , 32,   5],
"American Ale Malt"                            :["Grain",           "Base malt",        2.53807 , 37.3, 6],
"Apple"                                        :["Fruit",           "Fruit",            0       , 5.6,  7],
"Apricot"                                      :["Fruit",           "Fruit",            0       , 4.05, 8],
"Apricot (dried)"                              :["Fruit",           "Fruit",            0       , 17.9, 9],
"Aromatic (Belgian)"                           :["Grain",           "Roasted malt",     38      , 33,   10],
"Aromatic Malt (American)"                     :["Grain",           "Base malt",        20      , 35,   11],
"Ashbourne Mild	American"	                     :["Grain",           "Base malt",        5.3     , 30,   12],
"Aurora Malt"                                  :["Grain",           "Base malt",        29.4416 , 37.2, 13],
"Banana"                                       :["Fruit",           "Fruit",            0       , 7.65, 14],
"Belgian Candi Sugar - Amber/Brown (60L)"      :["Sugar",           "Sugar",            60      , 38,   15],
"Belgian Candi Sugar - Clear/Blond (0L)"       :["Sugar",           "Sugar",            0       , 38,   16],
"Belgian Candi Sugar - Dark (275L)"            :["Sugar",           "Sugar",            275     , 38,   17],
"Belgian Candi Syrup - Amber (40L)"            :["Sugar",           "Sugar",            40      , 32,   18],
"Belgian Candi Syrup - Clear (0L)"             :["Sugar",           "Sugar",            0       , 32,   19],
"Belgian Candi Syrup - D-180"                  :["Sugar",           "Sugar",            180     , 32,   20],
"Belgian Candi Syrup - D-45"                   :["Sugar",           "Sugar",            45      , 32,   21],
"Belgian Candi Syrup - D-90"                   :["Sugar",           "Sugar",            90      , 32,   22],
"Belgian Candi Syrup - D2 (160L)"              :["Sugar",           "Sugar",            160     , 32,   23],
"Belgian Candi Syrup - Dark (80L)"             :["Sugar",           "Sugar",            80      , 32,   24],
"Belgian Candi Syrup - Golden (5L)"            :["Sugar",           "Sugar",            5       , 32,   25],
"Biscuit (Belgian)"                            :["Grain",           "Roasted malt",     23      , 35,   26],
"Biscuit Malt"                                 :["Grain",           "Roasted malt",     30.4569 , 35,   27],
"Black Barley"                                 :["Grain",           "Roasted malt",     530     , 27,   28],
"Black Malt (American)"                        :["Grain",           "Roasted malt",     500     , 28,   29],
"Black Malt (Finland)"                         :["Grain",           "Roasted malt",     526     , 30,   30],
"Black Patent"                                 :["Grain",           "Roasted malt",     525     , 27,   31],
"Blackberry"                                   :["Fruit",           "Fruit",            0       , 3.6,  32],
"Blackprinz"                                   :["Grain",           "Roasted malt",     500     , 36,   33],
"Blueberry"                                    :["Fruit",           "Fruit",            0       , 4.95, 34],
"Bohemian Pilsner"                             :["Grain",           "Base malt",        1.9     , 38,   35],
"Bonlander Munich"                             :["Grain",           "Base malt",        10      , 36,   36],
"Boysenberry"                                  :["Fruit",           "Fruit",            0       , 2.5,  37],
"Brown (United Kingdom)"                       :["Grain",           "Roasted malt",     65      , 32,   38],
"Brown Malt (New Zealand)"                     :["Grain",           "Roasted malt",     90.3553 , 34,   39],
"Brown Rice Syrup (Gluten Free)"	             :["Sugar",           "Raw",              2       , 44,   40],
"Brown Sugar"                                  :["Sugar",           "Sugar",            15      , 45,   41],
"Buckwheat Malt (Gluten Free)"                 :["Grain",	          "Gluten-free",      2       , 25,   42],
"Cane Sugar"                                   :["Sugar",           "Sugar",            0       , 46,   43],
"Cantaloupe"                                   :["Fruit",           "Fruit",            0       , 3.4,  44],
"Cara 20L"                                     :["Grain",           "Crystal malt",     22      , 34,   45],
"Cara 45L"                                     :["Grain",           "Crystal malt",     42      , 34,   46],
"Cara Malt"                                    :["Grain",           "Crystal malt",     17.5    , 35,   47],
"Cara Pale"                                    :["Grain",           "Crystal malt",     4       , 35,   48],
"Cara Plus 100"                                :["Grain",           "Crystal malt",     38      , 35,   49],
"Cara Plus 150"                                :["Grain",           "Crystal malt",     57      , 35,   50],
"Cara Plus 200"                                :["Grain",           "Crystal malt",     76      , 35,   51],
"Cara Plus 250"                                :["Grain",           "Crystal malt",     94      , 35,   52],
"CaraAmber"                                    :["Grain",           "Crystal malt",     23      , 34,   53],
"CaraAroma"                                    :["Grain",           "Crystal malt",     130     , 34,   54],
"CaraBelge"                                    :["Grain",           "Crystal malt",     13.6    , 33,   55],
"CaraBohemian"                                 :["Grain",           "Crystal malt",     75      , 33,   56],
"CaraBrown"                                    :["Grain",           "Roasted malt",     55      , 34,   57],
"CaraCrystal Wheat Malt"                       :["Grain",           "Crystal malt",     55      , 34,   58],
"Carafa I"                                     :["Grain",           "Roasted malt",     340     , 32,   59],
"Carafa II"                                    :["Grain",           "Roasted malt",     425     , 32,   60],
"Carafa III"                                   :["Grain",           "Roasted malt",     535     , 32,   61],
"CaraFoam"                                     :["Grain",           "Crystal malt",     1.8     , 37,   62],
"CaraHell"                                     :["Grain",           "Crystal malt",     11      , 34,   63],
"Carambola"                                    :["Fruit",           "Fruit",            0       , 1.95, 64],
"Caramel/Crystal 10L"                          :["Grain",           "Crystal malt",     10      , 35,   65],
"Caramel/Crystal 120L"                         :["Grain",           "Crystal malt",     120     , 33,   66],
"Caramel/Crystal 150L"                         :["Grain",           "Crystal malt",     150     , 33,   67],
"Caramel/Crystal 15L"                          :["Grain",           "Crystal malt",     15      , 35,   68],
"Caramel/Crystal 20L"                          :["Grain",           "Crystal malt",     20      , 35,   69],
"Caramel/Crystal 30L"                          :["Grain",           "Crystal malt",     30      , 34,   70],
"Caramel/Crystal 40L"                          :["Grain",           "Crystal malt",     40      , 34,   71],
"Caramel/Crystal 60L"                          :["Grain",           "Crystal malt",     60      , 34,   72],
"Caramel/Crystal 75L"                          :["Grain",           "Crystal malt",     75      , 33,   73],
"Caramel/Crystal 80L"                          :["Grain",           "Crystal malt",     80      , 33,   74],
"Caramel/Crystal 90L"                          :["Grain",           "Crystal malt",     90      , 33,   75],
"Caramel Pils"                                 :["Grain",           "Crystal malt",     8       , 34,   76],
"Caramel Pils"                                 :["Grain",           "Crystal malt",     2.4     , 35,   77],
"Caramel Wheat"                                :["Grain",           "Crystal malt",     46      , 34,   78],
"CaraMunich"                                   :["Grain",           "Crystal malt",     50      , 33,   79],
"CaraMunich I"                                 :["Grain",           "Crystal malt",     39      , 34,   80],
"CaraMunich II"                                :["Grain",           "Crystal malt",     46      , 34,   81],
"CaraMunich III"                               :["Grain",           "Crystal malt",     57      , 34,   82],
"Carapils"                                     :["Grain",           "Crystal malt",     1.3     , 35,   83],
"Carapils (Dextrine Malt)"                     :["Grain",           "Crystal malt",     1.8     , 33,   84],
"CaraRed"                                      :["Grain",           "Crystal malt",     20      , 34,   85],
"Carastan (30/37)"                             :["Grain",           "Crystal malt",     34      , 35,   86],
"Carastan Light (15L)"                         :["Grain",           "Crystal malt",     15      , 35,   87],
"CaraVienne"                                   :["Grain",           "Crystal malt",     20      , 34,   88],
"Carrot"                                       :["Fruit",           "Fruit",            0       , 2,    89],
"Casaba Melon"                                 :["Fruit",           "Fruit",            0       , 1.9,  90],
"Cashew"                                       :["Fruit",           "Fruit",            0       , 3,    91],
"Celery"                                       :["Fruit",           "Fruit",            0       , 0.75, 92],
"Cherry"                                       :["Fruit",           "Fruit",            0       , 6.3,  93],
"Cherry, dark sweet"                           :["Fruit",           "Fruit",            0       , 6.4,  94],
"Cherry, Montmorency"                          :["Fruit",           "Fruit",            0       , 3.55, 95],
"Chocolate (American)"                         :["Grain",           "Roasted malt",     350     , 29,   96],
"Chocolate (Belgian)"                          :["Grain",           "Roasted malt",     340     , 30,   97],
"Chocolate (United Kingdom)"                   :["Grain",           "Roasted malt",     425     , 34,   98],
"Chocolate Malt (Finland)"                     :["Grain",           "Roasted malt",     338     , 31,   99],
"Chocolate Rye"                                :["Grain",           "Roasted malt",     240     , 31,   100],
"Chocolate Wheat"                              :["Grain",           "Roasted malt",     413     , 31,   101],
"Coffee Malt"                                  :["Grain",           "Roasted malt",     150     , 36,   102],
"Cookie Malt"                                  :["Grain",           "Roasted malt",     19      , 37,   103],
"Corn Sugar (Dextrose)"                        :["Sugar",           "Sugar",            0.5     , 46,   104],
"Corn Syrup"                                   :["Sugar",           "Sugar",            0.5     , 37,   105],
"Crabapple"                                    :["Fruit",           "Fruit",            0       , 3.85, 106],
"Cranberry"                                    :["Fruit",           "Fruit",            0       , 1.8,  107],
"Crystal 10L Millet Malt (Gluten Free)"        :["Grain",           "Gluten-free",      10      , 25,   108],
"Crystal 140L (United Kingdom)"                :["Grain",           "Crystal malt",     140     , 33,   109],
"Crystal 15L (United Kingdom)"                 :["Grain",           "Crystal malt",     15      , 34,   110],
"Crystal 30L (United Kingdom)"                 :["Grain",           "Crystal malt",     30      , 34,   111],
"Crystal 30L Millet Malt (Gluten Free)"        :["Grain",           "Gluten-free",      30      , 25,   112],
"Crystal 45L (United Kingdom)"                 :["Grain",           "Crystal malt",     45      , 34,   113],
"Crystal 50L (United Kingdom)"                 :["Grain",           "Crystal malt",     50      , 34,   114],
"Crystal 60L (United Kingdom)"                 :["Grain",           "Crystal malt",     60      , 34,   115],
"Crystal 70L (United Kingdom)"                 :["Grain",           "Crystal malt",     70      , 34,   116],
"Crystal 90L (United Kingdom)"                 :["Grain",           "Crystal malt",     90      , 33,   117],
"Crystal Malt 100 (Finland)"                   :["Grain",           "Crystal malt",     38      , 35,   118],
"Crystal Malt 150 (Finland)"                   :["Grain",           "Crystal malt",     57      , 35,   119],
"Crystal Malt 250 (Finland)"                   :["Grain",           "Crystal malt",     94      , 35,   120],
"Crystal Malt 300 (Finland)"                   :["Grain",           "Crystal malt",     113     , 35,   121],
"Crystal Malt 50 (Finland)"                    :["Grain",           "Crystal malt",     19      , 35,   122],
"Crystal Rye (United Kingdom)"                 :["Grain",           "Crystal malt",     90      , 33,   123],
"Currant, black"                               :["Fruit",           "Fruit",            0       , 4.2,  124],
"Currant, red"                                 :["Fruit",           "Fruit",            0       , 2.7,  125],
"Dark Ale"                                     :["Grain",           "Roasted malt",     14      , 35,   126],
"Dark Chocolate (American)"                    :["Grain",           "Roasted malt",     420     , 29,   127],
"Dark Chocolate Malt (New Zealand)"            :["Grain",           "Roasted malt",     659.898 , 32.7, 128],
"Dark Crystal 80L (United Kingdom)"            :["Grain",           "Crystal malt",     80      , 33,   129],
"Dark Crystal Malt (New Zealand)"              :["Grain",           "Crystal malt",     96.4467 , 35.4, 130],
"Dark Munich"                                  :["Grain",           "Base malt",        10      , 36,   131],
"Dark Roasted Millet Malt (Gluten Free)"       :["Grain",           "Gluten-free",      300     , 25,   132],
"Dark Wheat"                                   :["Grain",           "Base malt",        6.5     , 39,   133],
"Date"                                         :["Fruit",           "Fruit",            0       , 27,   134],
"Date (dried)"                                 :["Fruit",           "Fruit",            0       , 28.9, 135],
"De-Bittered Black"                            :["Grain",           "Roasted malt",     566     , 34,   136],
"De-Husked Caraf I"                            :["Grain",           "Roasted malt",     340     , 32,   137],
"De-Husked Caraf II"                           :["Grain",           "Roasted malt",     418     , 32,   138],
"De-Husked Caraf III"                          :["Grain",           "Roasted malt",     470     , 32,   139],
"Dewberry"                                     :["Fruit",           "Fruit",            0       , 2.5,  140],
"Dextrine Malt"                                :["Grain",           "Crystal malt",     1.8     , 33,   141],
"Distillers Malt"                              :["Grain",           "Base malt",        2       , 37,   142],
"Dry Malt Extract (Amber)"                     :["Dry Extract",     "Extract",          10      , 42,   143],
"Dry Malt Extract (Dark)"                      :["Dry Extract",     "Extract",          30      , 44,   144],
"Dry Malt Extract (Extra Light)"               :["Dry Extract",     "Extract",          2.5     , 42,   145],
"Dry Malt Extract (Light)"                     :["Dry Extract",     "Extract",          4       , 42,   146],
"Dry Malt Extract (Munich)"                    :["Dry Extract",     "Extract",          8       , 42,   147],
"Dry Malt Extract (Pilsen)"                    :["Dry Extract",     "Extract",          2       , 42,   148],
"Dry Malt Extract (Wheat)"                     :["Dry Extract",     "Extract",          3       , 42,   149],
"Elderberry"                                   :["Fruit",           "Fruit",            0       , 2.75, 150],
"Enzyme Malt"                                  :["Grain",           "Base malt",        0       , 35,   151],
"ESB Malt"                                     :["Grain",           "Base malt",        3.5     , 36,   152],
"Extra Dark Crystal 120L"                      :["Grain",           "Crystal malt",     120     , 33,   153],
"Extra Dark Crystal 160L"                      :["Grain",           "Crystal malt",     160     , 33,   154],
"Fig"                                          :["Fruit",           "Fruit",            0       , 5.3,  155],
"Figs (dried)"                                 :["Fruit",           "Fruit",            0       , 29.95,156],
"Flaked Barley"                                :["Adjunct",         "Raw",              2.2     , 32,   157],
"Flaked Corn"                                  :["Adjunct",         "Raw",              0.5     , 40,   158],
"Flaked Oats"                                  :["Adjunct",         "Raw",              2.2     , 33,   159],
"Flaked Rice"                                  :["Adjunct",         "Raw",              0.5     , 40,   160],
"Flaked Rye"                                   :["Adjunct",         "Raw",              2.8     , 36,   161],
"Flaked Wheat"                                 :["Adjunct",         "Raw",              2       , 34,   162],
"Floor-Malted Bohemian Pilsner"                :["Grain",           "Base malt",        1.8     , 38,   163],
"Floor-Malted Bohemian Pilsner Dk"             :["Grain",           "Base malt",        6.5     , 38,   164],
"Floor-Malted Bohemian Wheat"                  :["Grain",           "Base malt",        2       , 38,   165],
"Gladiator Malt"                               :["Grain",           "Base malt",        5.07614 , 37.3, 166],
"Golden Naked Oats"                            :["Grain",           "Raw",              10      , 33,   167],
"Golden Promise"                               :["Grain",           "Base malt",        3       , 37,   168],
"Gooseberry"                                   :["Fruit",           "Fruit",            0       , 4.95, 169],
"Grape"                                        :["Fruit",           "Fruit",            0       , 7.15, 170],
"Grape, concord"                               :["Fruit",           "Fruit",            0       , 4,    171],
"Grapefruit"                                   :["Fruit",           "Fruit",            0       , 2.75, 172],
"Grits"                                        :["Adjunct",         "Raw",              1       , 37,   173],
"Guanabana"                                    :["Fruit",           "Fruit",            0       , 4,    174],
"Guava"                                        :["Fruit",           "Fruit",            0       , 2.8,  175],
"Halcyon"                                      :["Grain",           "Base malt",        2       , 36,   176],
"Honey"                                        :["Sugar",           "Sugar",            2       , 42,   177],
"Honey (Buckwheat)"                            :["Sugar",           "Sugar",            2       , 42,   178],
"Honey Malt"                                   :["Grain",           "Base malt",        25      , 37,   179],
"Honeydew Melon"                               :["Fruit",           "Fruit",            0       , 4.5,  180],
"Invert Sugar"                                 :["Sugar",           "Sugar",            1       , 46,   181],
"Jackfruit"                                    :["Fruit",           "Fruit",            0       , 8.3,  182],
"Kiwi"                                         :["Fruit",           "Fruit",            0       , 5.75, 183],
"Kolsch"                                       :["Grain",           "Base malt",        4.4     , 37,   184],
"Lactose"                                      :["Sugar",           "Sugar",            1       , 41,   185],
"Lager (United Kingdom)"                       :["Grain",           "Base malt",        1.4     , 38,   186],
"Lager Light (New Zealand)"                    :["Grain",           "Base malt",        1.4264  , 37,   187],
"Lager Malt (Ireland)"                         :["Grain",           "Base malt",        2       , 37,   188],
"Lemon juice"                                  :["Fruit",           "Fruit",            0       , 1,    189],
"Light Chocolate Malt"                         :["Grain",           "Roasted malt",     456.853 , 32.7, 190],
"Light Crystal Malt"                           :["Grain",           "Crystal malt",     31.9797 , 35.4, 191],
"Light Roasted Millet Malt (Gluten Free)"      :["Grain",           "Gluten-free",      7       , 25,   192],
"Lime"                                         :["Fruit",           "Fruit",            0       , 0.45, 193],
"Lime juice"                                   :["Fruit",           "Fruit",            0       , 0.45, 194],
"Liquid Malt Extract (Amber)"                  :["Liquid Extract",  "Extract",          10      , 35,   195],
"Liquid Malt Extract (Dark)"                   :["Liquid Extract",  "Extract",          30      , 35,   196],
"Liquid Malt Extract (Extra Light)"            :["Liquid Extract",  "Extract",          2.5     , 37,   197],
"Liquid Malt Extract (Light)"                  :["Liquid Extract",  "Extract",          4       , 35,   198],
"Liquid Malt Extract (Maris Otter)"            :["Liquid Extract",  "Extract",          4       , 36,   199],
"Liquid Malt Extract (Munich)"                 :["Liquid Extract",  "Extract",          8       , 35,   200],
"Liquid Malt Extract (Pilsen)"                 :["Liquid Extract",  "Extract",          2       , 35,   201],
"Liquid Malt Extract (Rye)"                    :["Liquid Extract",  "Extract",          9       , 35,   202],
"Liquid Malt Extract (Wheat)"                  :["Liquid Extract",  "Extract",          3       , 35,   203],
"Loganberry"                                   :["Fruit",           "Fruit",            0       , 2.6,  204],
"Lychee (Litchi)"                              :["Fruit",           "Fruit",            0       , 7.65, 205],
"Malted Naked Oats"                            :["Grain",           "Base malt",        1.3     , 33,   206],
"Malted Rye"                                   :["Grain",           "Base malt",        3       , 40.2, 207],
"Maltodextrin"                                 :["Sugar",           "Sugar",            0       , 39,   208],
"Mango"                                        :["Fruit",           "Fruit",            0       , 4.95, 209],
"Manuka Smoked Malt"                           :["Grain",           "Base malt",        2.03046 , 36.8, 210],
"Maple Sap"                                    :["Fruit",           "Fruit",            0       , 0.9,  211],
"Maple Syrup"                                  :["Fruit",           "Fruit",            0       , 29.8, 212],
"Maple Syrup"                                  :["Sugar",           "Sugar",            35      , 30,   213],
"Maris Otter Pale"                             :["Grain",           "Base malt",        3.75    , 38,   214],
"Medium Crystal Malt"                          :["Grain",           "Crystal malt",     56.3452 , 35.4, 215],
"Medium Roasted Millet Malt (Gluten Free)"     :["Grain",           "Gluten-free",      36      , 25,   216],
"Melanoid Malt"                                :["Grain",           "Roasted malt",     27      , 35,   217],
"Melanoidin"                                   :["Grain",           "Roasted malt",     25      , 37,   218],
"Midnight Wheat Malt"                          :["Grain",           "Roasted malt",     550     , 33,   219],
"Mild"                                         :["Grain",           "Base malt",        3       , 37,   220],
"Molasses"                                     :["Sugar",           "Sugar",            80      , 36,   221],
"Mulberry"                                     :["Fruit",           "Fruit",            0       , 6.1,  222],
"Munich (Belgian)"                             :["Grain",           "Base malt",        6       , 38,   223],
"Munich (United Kingdom)"	                     :["Grain",           "Base malt",        6       , 37,   224],
"Munich - 60L (American)"	                     :["Grain",           "Base malt",        60      , 33,   225],
"Munich - Dark 20L (American)"                 :["Grain",           "Base malt",        20      , 33,   226],
"Munich - Light 10L (American)"                :["Grain",           "Base malt",        10      , 33,   227],
"Munich Dark (Canadian)"                       :["Grain",           "Base malt",        32      , 34,   228],
"Munich Dark (German)"                         :["Grain",           "Base malt",        15.5    , 37,   229],
"Munich Light (Canadian)"                      :["Grain",           "Base malt",        10      , 34,   230],
"Munich Light (German)"                        :["Grain",           "Base malt",        6       , 37,   231],
"Munich Malt (New Zealand)"                    :["Grain",           "Base malt",        7.86802 , 36.8, 232],
"Munich Malt (Finland)"                        :["Grain",           "Base malt",        7       , 36,   233],
"Munich Millet Malt (Gluten Free,American)"    :["Grain",           "Gluten-free",      7       , 25,   234],
"Nectarine"                                    :["Fruit",           "Fruit",            0       , 3.4,  235],
"Oat Malt"                                     :["Grain",           "Base malt",        2       , 28,   236],
"Optic"                                        :["Grain",           "Base malt",        2.1     , 38,   237],
"Orange"                                       :["Fruit",           "Fruit",            0       , 4.1,  238],
"Orange (Blood Orange)"                        :["Fruit",           "Fruit",            0       , 4.05, 239],
"Orange juice"                                 :["Fruit",           "Fruit",            0       , 4.8,  240],
"Organic Pilsner (New Zealand)"                :["Grain",           "Base malt",        1.58629 , 37.9, 241],
"Organic Pilsner Malt (Finland)"               :["Grain",           "Base malt",        2       , 36,   242],
"Pale 2-Row (American)"                        :["Grain",           "Base malt",        1.8     , 37,   243],
"Pale 2-Row (Canadian)"                        :["Grain",           "Base malt",        1.75    , 36,   244],
"Pale 2-Row (United Kingdom)"                  :["Grain",           "Base malt",        2.5     , 38,   245],
"Pale 2-Row (Toasted,American)"                :["Grain",           "Base malt",        30      , 33,   246],
"Pale 6-Row"                                   :["Grain",           "Base malt",        1.8     , 35,   247],
"Pale Ale (American)"                          :["Grain",           "Base malt",        3.5     , 37,   248],
"Pale Ale (Belgian)"                           :["Grain",           "Base malt",        3.4     , 38,   249],
"Pale Ale (German)"                            :["Grain",           "Base malt",        2.3     , 39,   250],
"Pale Ale Malt (Finland)"                      :["Grain",           "Base malt",        2       , 36,   251],
"Pale Chocolate"                               :["Grain",           "Roasted malt",     207     , 33,   252],
"Pale Millet Malt (Gluten Free)"               :["Grain",           "Gluten-free",      1.5     , 30,   253],
"Pale Wheat (Canadian)"                        :["Grain",           "Base malt",        2       , 36,   254],
"Pale Wheat (German)"                          :["Grain",           "Base malt",        1.5     , 39,   255],
"Papaya"                                       :["Fruit",           "Fruit",            0       , 2.9,  256],
"Passionfruit"                                 :["Fruit",           "Fruit",            0       , 5,    257],
"Peach"                                        :["Fruit",           "Fruit",            0       , 4.05, 258],
"Pear"                                         :["Fruit",           "Fruit",            0       , 4.5,  259],
"Pearl"                                        :["Grain",           "Base malt",        2.1     , 37,   260],
"Peated Malt"                                  :["Grain",           "Base malt",        2.5     , 38,   261],
"Persimmon"                                    :["Fruit",           "Fruit",            0       , 6.3,  262],
"Pilsen"                                       :["Grain",           "Base malt",        1.8     , 36,   263],
"Pilsner (American)"                           :["Grain",           "Base malt",        1.8     , 37,   264],
"Pilsner (Belgian)"                            :["Grain",           "Base malt",        1.6     , 37,   265],
"Pilsner (German)"                             :["Grain",           "Base malt",        1.6     , 38,   266],
"Pilsner Malt (New Zealand)"                   :["Grain",           "Base malt",        1.92893 , 37.3, 267],
"Pilsner Malt (Finland)"                       :["Grain",           "Base malt",        2       , 37,   268],
"Pineapple"                                    :["Fruit",           "Fruit",            0       , 5.85, 269],
"Plum"                                         :["Fruit",           "Fruit",            0       , 4.95, 270],
"Pomegranate"                                  :["Fruit",           "Fruit",            0       , 5.2,  271],
"Prickly Pear"                                 :["Fruit",           "Fruit",            0       , 4.95, 272],
"Prunes (dried)"                               :["Fruit",           "Fruit",            0       , 19.8, 273],
"Pumpkin (canned)"                             :["Fruit",           "Fruit",            0       , 1,    274],
"Pumpkin (fresh)"                              :["Fruit",           "Fruit",            0       , 1,    275],
"Quince"                                       :["Fruit",           "Fruit",            0       , 0.45, 276],
"Raisins (dried)"                              :["Fruit",           "Fruit",            0       , 29.25,277],
"Raspberry"                                    :["Fruit",           "Fruit",            0       , 3.15, 278],
"Raspberry (black)"                            :["Fruit",           "Fruit",            0       , 2.8,  279],
"Raspberry (red)"                              :["Fruit",           "Fruit",            0       , 2.3,  280],
"Red Back Malt"                                :["Grain",           "Roasted malt",     32.9949 , 35.4, 281],
"Red Wheat"                                    :["Grain",           "Base malt",        2.5     , 38,   282],
"Red X"                                        :["Grain",           "Base malt",        12      , 36,   283],
"Rhubarb"                                      :["Fruit",           "Fruit",            0       , 0.4,  284],
"Rice Hulls"                                   :["Adjunct",         "Other",            0       , 0,    285],
"Rice Syrup Solids"                            :["Dry Extract",     "Raw",              1       , 37,   286],
"Roast Barley (New Zealand)"                   :["Grain",           "Roasted malt",     736.041 , 32.7, 287],
"Roasted Barley (American)"                    :["Grain",           "Roasted malt",     300     , 33,   288],
"Roasted Barley (Belgian)"                     :["Grain",           "Roasted malt",     575     , 30,   289],
"Roasted Barley (United Kingdom)"              :["Grain",           "Roasted malt",     550     , 29,   290],
"Roasted Wheat"                                :["Grain",           "Roasted malt",     279.188 , 33.6, 291],
"Rolled Barley"                                :["Adjunct",         "Raw",              1.7     , 35.4, 292],
"Rolled Oats"                                  :["Adjunct",         "Raw",              2.2     , 33,   293],
"Rolled Oats (New Zealand)"                    :["Adjunct",         "Raw",              1.4     , 12.4, 294],
"Rye (American)"                               :["Grain",           "Base malt",        3.5     , 38,   295],
"Rye (German)"                                 :["Grain",           "Base malt",        3.5     , 38,   296],
"Shepherds Delight Malt"                       :["Grain",           "Roasted malt",     152.284 , 36.5, 297],
"Smoked Malt (America)"                        :["Grain",           "Base malt",        5       , 37,   298],
"Smoked Malt (German)"                         :["Grain",           "Base malt",        3       , 37,   299],
"Soft Candi Sugar (Blond)"                     :["Sugar",           "Sugar",            5       , 38,   300],
"Soft Candi Sugar (Brown)"                     :["Sugar",           "Sugar",            60      , 38,   301],
"Sour Grapes Malt"                             :["Grain",           "Base malt",        2.03046 , 34,   302],
"Special B"                                    :["Grain",           "Roasted malt",     115     , 34,   303],
"Special Roast"                                :["Grain",           "Roasted malt",     50      , 33,   304],
"Spelt Malt"                                   :["Grain",           "Base malt",        2       , 37,   305],
"Stout Malt"                                   :["Grain",           "Base malt",        2       , 37,   306],
"Strawberry"                                   :["Fruit",           "Fruit",            0       , 3.15, 307],
"Sultanas"                                     :["Fruit",           "Fruit",            0       , 8.55, 308],
"Supernova Malt"                               :["Grain",           "Roasted malt",     58.3756 , 37.4, 309],
"Tangelo"                                      :["Fruit",           "Fruit",            0       , 3.35, 310],
"Tangerine"                                    :["Fruit",           "Fruit",            0       , 2.95, 311],
"Toffee Malt"                                  :["Grain",           "Roasted malt",     5.32995 , 38.8, 312],
"Tomato"                                       :["Fruit",           "Fruit",            0       , 1.25, 313],
"Torrified Barley"                             :["Adjunct",         "Raw",              2       , 36,   314],
"Torrified Wheat"                              :["Adjunct",         "Raw",              2       , 36,   315],
"Turbinado"                                    :["Sugar",           "Sugar",            10      , 44,   316],
"Unmalted Wheat"                               :["Grain",           "Raw",              2       , 36,   317],
"Victory"                                      :["Grain",           "Roasted malt",     28      , 34,   318],
"Vienna (American)"                            :["Grain",           "Base malt",        4       , 35,   319],
"Vienna (German)"                              :["Grain",           "Base malt",        4       , 37,   320],
"Vienna Malt (New Zealand)"                    :["Grain",           "Base malt",        3.45178 , 39.1, 321],
"Vienna Malt (Finland)"                        :["Grain",           "Base malt",        3       , 36,   322],
"Watermelon"                                   :["Fruit",           "Fruit",            0       , 4.05, 323],
"Wheat (American)"                             :["Grain",           "Base malt",        1.8     , 38,   324],
"Wheat (Belgian)"                              :["Grain",           "Base malt",        1.8     , 38,   325],
"Wheat (United Kingdom)"                       :["Grain",           "Base malt",        2       , 37,   326],
"Wheat Malt (New Zealand)"                     :["Grain",           "Base malt",        2.13198 , 35.4, 327],
"Wheat Malt (German)"                          :["Grain",           "Base malt",        2       , 37,   328],
"Wheat Malt (Finland)"                         :["Grain",           "Base malt",        2       , 38,   329],
"White Sorghum Syrup (Gluten Free)"            :["Sugar",           "Sugar",            1.5     , 37,   330],
"White Wheat"                                  :["Grain",           "Base malt",        2.8     , 40,   331],
"Youngberry"                                   :["Fruit",           "Fruit",            0       , 2.5,  332]
}
